version: '3'

services:
  tenhou_log_db:
    image: postgres:15.4
    container_name: tenhou-log-db
    ports:
      - "65432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./services/database/data:/var/lib/postgresql/data
      - ./services/database/logs:/var/log
  test_tenhou_log_db:
    image: postgres:15.4
    container_name: tenhou-log-db-test
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres_test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./services/database/test_data:/var/lib/postgresql/data
  terraform:
    container_name: tenhou-log-terraform
    build: infra/terraform
    working_dir: /terraform
    tty: true
    volumes:
      - ./infra/terraform:/terraform:cached
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: bash
    environment:
      HOME: "/terraform"
  backend:
    image: hasura/graphql-engine:v2.33.4
    ports:
      - "8080:8080"
    depends_on:
      - tenhou_log_db
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:secret@tenhou-log-db:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:secret@tenhou-log-db:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
