version: '3'

services:
  tenhou_log_db:
    image: postgres:15.0
    container_name: tenhou-log-db
    ports:
      - "65432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./services/database/data:/var/lib/postgresql/data
      - ./services/database/logs:/var/log
  test_tenhou_log_db:
    image: postgres:15.0
    container_name: tenhou-log-db-test
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres_test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./services/database/test_data:/var/lib/postgresql/data
  terraform:
    container_name: tenhou-log-terraform
    build: infra/terraform
    working_dir: /terraform
    tty: true
    volumes:
      - ./infra/terraform:/terraform:cached
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: bash
    environment:
      HOME: "/terraform"
