// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanade0404/tenhou-log/services/ent/gameplayerpoint"
)

// GamePlayerPoint is the model entity for the GamePlayerPoint schema.
type GamePlayerPoint struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Point holds the value of the "point" field.
	Point uint `json:"point,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GamePlayerPoint) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gameplayerpoint.FieldPoint:
			values[i] = new(sql.NullInt64)
		case gameplayerpoint.FieldID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type GamePlayerPoint", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GamePlayerPoint fields.
func (gpp *GamePlayerPoint) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gameplayerpoint.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				gpp.ID = *value
			}
		case gameplayerpoint.FieldPoint:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field point", values[i])
			} else if value.Valid {
				gpp.Point = uint(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this GamePlayerPoint.
// Note that you need to call GamePlayerPoint.Unwrap() before calling this method if this GamePlayerPoint
// was returned from a transaction, and the transaction was committed or rolled back.
func (gpp *GamePlayerPoint) Update() *GamePlayerPointUpdateOne {
	return (&GamePlayerPointClient{config: gpp.config}).UpdateOne(gpp)
}

// Unwrap unwraps the GamePlayerPoint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gpp *GamePlayerPoint) Unwrap() *GamePlayerPoint {
	_tx, ok := gpp.config.driver.(*txDriver)
	if !ok {
		panic("ent: GamePlayerPoint is not a transactional entity")
	}
	gpp.config.driver = _tx.drv
	return gpp
}

// String implements the fmt.Stringer.
func (gpp *GamePlayerPoint) String() string {
	var builder strings.Builder
	builder.WriteString("GamePlayerPoint(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gpp.ID))
	builder.WriteString("point=")
	builder.WriteString(fmt.Sprintf("%v", gpp.Point))
	builder.WriteByte(')')
	return builder.String()
}

// GamePlayerPoints is a parsable slice of GamePlayerPoint.
type GamePlayerPoints []*GamePlayerPoint

func (gpp GamePlayerPoints) config(cfg config) {
	for _i := range gpp {
		gpp[_i].config = cfg
	}
}
