// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanade0404/tenhou-log/services/ent/mjlog"
	"github.com/kanade0404/tenhou-log/services/ent/mjlogfile"
	"github.com/kanade0404/tenhou-log/services/ent/predicate"
)

// MJLogUpdate is the builder for updating MJLog entities.
type MJLogUpdate struct {
	config
	hooks    []Hook
	mutation *MJLogMutation
}

// Where appends a list predicates to the MJLogUpdate builder.
func (mlu *MJLogUpdate) Where(ps ...predicate.MJLog) *MJLogUpdate {
	mlu.mutation.Where(ps...)
	return mlu
}

// SetMjlogFilesID sets the "mjlog_files" edge to the MJLogFile entity by ID.
func (mlu *MJLogUpdate) SetMjlogFilesID(id uuid.UUID) *MJLogUpdate {
	mlu.mutation.SetMjlogFilesID(id)
	return mlu
}

// SetNillableMjlogFilesID sets the "mjlog_files" edge to the MJLogFile entity by ID if the given value is not nil.
func (mlu *MJLogUpdate) SetNillableMjlogFilesID(id *uuid.UUID) *MJLogUpdate {
	if id != nil {
		mlu = mlu.SetMjlogFilesID(*id)
	}
	return mlu
}

// SetMjlogFiles sets the "mjlog_files" edge to the MJLogFile entity.
func (mlu *MJLogUpdate) SetMjlogFiles(m *MJLogFile) *MJLogUpdate {
	return mlu.SetMjlogFilesID(m.ID)
}

// Mutation returns the MJLogMutation object of the builder.
func (mlu *MJLogUpdate) Mutation() *MJLogMutation {
	return mlu.mutation
}

// ClearMjlogFiles clears the "mjlog_files" edge to the MJLogFile entity.
func (mlu *MJLogUpdate) ClearMjlogFiles() *MJLogUpdate {
	mlu.mutation.ClearMjlogFiles()
	return mlu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mlu *MJLogUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mlu.hooks) == 0 {
		affected, err = mlu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MJLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mlu.mutation = mutation
			affected, err = mlu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mlu.hooks) - 1; i >= 0; i-- {
			if mlu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mlu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mlu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mlu *MJLogUpdate) SaveX(ctx context.Context) int {
	affected, err := mlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mlu *MJLogUpdate) Exec(ctx context.Context) error {
	_, err := mlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mlu *MJLogUpdate) ExecX(ctx context.Context) {
	if err := mlu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mlu *MJLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mjlog.Table,
			Columns: mjlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: mjlog.FieldID,
			},
		},
	}
	if ps := mlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if mlu.mutation.MjlogFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mjlog.MjlogFilesTable,
			Columns: []string{mjlog.MjlogFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: mjlogfile.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mlu.mutation.MjlogFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mjlog.MjlogFilesTable,
			Columns: []string{mjlog.MjlogFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: mjlogfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mjlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// MJLogUpdateOne is the builder for updating a single MJLog entity.
type MJLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MJLogMutation
}

// SetMjlogFilesID sets the "mjlog_files" edge to the MJLogFile entity by ID.
func (mluo *MJLogUpdateOne) SetMjlogFilesID(id uuid.UUID) *MJLogUpdateOne {
	mluo.mutation.SetMjlogFilesID(id)
	return mluo
}

// SetNillableMjlogFilesID sets the "mjlog_files" edge to the MJLogFile entity by ID if the given value is not nil.
func (mluo *MJLogUpdateOne) SetNillableMjlogFilesID(id *uuid.UUID) *MJLogUpdateOne {
	if id != nil {
		mluo = mluo.SetMjlogFilesID(*id)
	}
	return mluo
}

// SetMjlogFiles sets the "mjlog_files" edge to the MJLogFile entity.
func (mluo *MJLogUpdateOne) SetMjlogFiles(m *MJLogFile) *MJLogUpdateOne {
	return mluo.SetMjlogFilesID(m.ID)
}

// Mutation returns the MJLogMutation object of the builder.
func (mluo *MJLogUpdateOne) Mutation() *MJLogMutation {
	return mluo.mutation
}

// ClearMjlogFiles clears the "mjlog_files" edge to the MJLogFile entity.
func (mluo *MJLogUpdateOne) ClearMjlogFiles() *MJLogUpdateOne {
	mluo.mutation.ClearMjlogFiles()
	return mluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mluo *MJLogUpdateOne) Select(field string, fields ...string) *MJLogUpdateOne {
	mluo.fields = append([]string{field}, fields...)
	return mluo
}

// Save executes the query and returns the updated MJLog entity.
func (mluo *MJLogUpdateOne) Save(ctx context.Context) (*MJLog, error) {
	var (
		err  error
		node *MJLog
	)
	if len(mluo.hooks) == 0 {
		node, err = mluo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MJLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mluo.mutation = mutation
			node, err = mluo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mluo.hooks) - 1; i >= 0; i-- {
			if mluo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mluo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mluo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*MJLog)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MJLogMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (mluo *MJLogUpdateOne) SaveX(ctx context.Context) *MJLog {
	node, err := mluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mluo *MJLogUpdateOne) Exec(ctx context.Context) error {
	_, err := mluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mluo *MJLogUpdateOne) ExecX(ctx context.Context) {
	if err := mluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mluo *MJLogUpdateOne) sqlSave(ctx context.Context) (_node *MJLog, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mjlog.Table,
			Columns: mjlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: mjlog.FieldID,
			},
		},
	}
	id, ok := mluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MJLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mjlog.FieldID)
		for _, f := range fields {
			if !mjlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mjlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if mluo.mutation.MjlogFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mjlog.MjlogFilesTable,
			Columns: []string{mjlog.MjlogFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: mjlogfile.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mluo.mutation.MjlogFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mjlog.MjlogFilesTable,
			Columns: []string{mjlog.MjlogFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: mjlogfile.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MJLog{config: mluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mjlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
