// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanade0404/tenhou-log/services/ent/mjlog"
	"github.com/kanade0404/tenhou-log/services/ent/predicate"
)

// MJLogDelete is the builder for deleting a MJLog entity.
type MJLogDelete struct {
	config
	hooks    []Hook
	mutation *MJLogMutation
}

// Where appends a list predicates to the MJLogDelete builder.
func (mld *MJLogDelete) Where(ps ...predicate.MJLog) *MJLogDelete {
	mld.mutation.Where(ps...)
	return mld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mld *MJLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, MJLogMutation](ctx, mld.sqlExec, mld.mutation, mld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mld *MJLogDelete) ExecX(ctx context.Context) int {
	n, err := mld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mld *MJLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mjlog.Table, sqlgraph.NewFieldSpec(mjlog.FieldID, field.TypeUUID))
	if ps := mld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mld.mutation.done = true
	return affected, err
}

// MJLogDeleteOne is the builder for deleting a single MJLog entity.
type MJLogDeleteOne struct {
	mld *MJLogDelete
}

// Where appends a list predicates to the MJLogDelete builder.
func (mldo *MJLogDeleteOne) Where(ps ...predicate.MJLog) *MJLogDeleteOne {
	mldo.mld.mutation.Where(ps...)
	return mldo
}

// Exec executes the deletion query.
func (mldo *MJLogDeleteOne) Exec(ctx context.Context) error {
	n, err := mldo.mld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mjlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mldo *MJLogDeleteOne) ExecX(ctx context.Context) {
	if err := mldo.Exec(ctx); err != nil {
		panic(err)
	}
}
