// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanade0404/tenhou-log/services/ent/compressedmjlog"
	"github.com/kanade0404/tenhou-log/services/ent/mjlogfile"
)

// MJLogFileCreate is the builder for creating a MJLogFile entity.
type MJLogFileCreate struct {
	config
	mutation *MJLogFileMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mlfc *MJLogFileCreate) SetName(s string) *MJLogFileCreate {
	mlfc.mutation.SetName(s)
	return mlfc
}

// SetID sets the "id" field.
func (mlfc *MJLogFileCreate) SetID(u uuid.UUID) *MJLogFileCreate {
	mlfc.mutation.SetID(u)
	return mlfc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mlfc *MJLogFileCreate) SetNillableID(u *uuid.UUID) *MJLogFileCreate {
	if u != nil {
		mlfc.SetID(*u)
	}
	return mlfc
}

// SetCompressedMjlogFilesID sets the "compressed_mjlog_files" edge to the CompressedMJLog entity by ID.
func (mlfc *MJLogFileCreate) SetCompressedMjlogFilesID(id uuid.UUID) *MJLogFileCreate {
	mlfc.mutation.SetCompressedMjlogFilesID(id)
	return mlfc
}

// SetCompressedMjlogFiles sets the "compressed_mjlog_files" edge to the CompressedMJLog entity.
func (mlfc *MJLogFileCreate) SetCompressedMjlogFiles(c *CompressedMJLog) *MJLogFileCreate {
	return mlfc.SetCompressedMjlogFilesID(c.ID)
}

// Mutation returns the MJLogFileMutation object of the builder.
func (mlfc *MJLogFileCreate) Mutation() *MJLogFileMutation {
	return mlfc.mutation
}

// Save creates the MJLogFile in the database.
func (mlfc *MJLogFileCreate) Save(ctx context.Context) (*MJLogFile, error) {
	var (
		err  error
		node *MJLogFile
	)
	mlfc.defaults()
	if len(mlfc.hooks) == 0 {
		if err = mlfc.check(); err != nil {
			return nil, err
		}
		node, err = mlfc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MJLogFileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mlfc.check(); err != nil {
				return nil, err
			}
			mlfc.mutation = mutation
			if node, err = mlfc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mlfc.hooks) - 1; i >= 0; i-- {
			if mlfc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mlfc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mlfc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*MJLogFile)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MJLogFileMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mlfc *MJLogFileCreate) SaveX(ctx context.Context) *MJLogFile {
	v, err := mlfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mlfc *MJLogFileCreate) Exec(ctx context.Context) error {
	_, err := mlfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mlfc *MJLogFileCreate) ExecX(ctx context.Context) {
	if err := mlfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mlfc *MJLogFileCreate) defaults() {
	if _, ok := mlfc.mutation.ID(); !ok {
		v := mjlogfile.DefaultID()
		mlfc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mlfc *MJLogFileCreate) check() error {
	if _, ok := mlfc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MJLogFile.name"`)}
	}
	if _, ok := mlfc.mutation.CompressedMjlogFilesID(); !ok {
		return &ValidationError{Name: "compressed_mjlog_files", err: errors.New(`ent: missing required edge "MJLogFile.compressed_mjlog_files"`)}
	}
	return nil
}

func (mlfc *MJLogFileCreate) sqlSave(ctx context.Context) (*MJLogFile, error) {
	_node, _spec := mlfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mlfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (mlfc *MJLogFileCreate) createSpec() (*MJLogFile, *sqlgraph.CreateSpec) {
	var (
		_node = &MJLogFile{config: mlfc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: mjlogfile.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: mjlogfile.FieldID,
			},
		}
	)
	if id, ok := mlfc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mlfc.mutation.Name(); ok {
		_spec.SetField(mjlogfile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := mlfc.mutation.CompressedMjlogFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   mjlogfile.CompressedMjlogFilesTable,
			Columns: []string{mjlogfile.CompressedMjlogFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: compressedmjlog.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.compressed_mj_log_mjlog_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MJLogFileCreateBulk is the builder for creating many MJLogFile entities in bulk.
type MJLogFileCreateBulk struct {
	config
	builders []*MJLogFileCreate
}

// Save creates the MJLogFile entities in the database.
func (mlfcb *MJLogFileCreateBulk) Save(ctx context.Context) ([]*MJLogFile, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mlfcb.builders))
	nodes := make([]*MJLogFile, len(mlfcb.builders))
	mutators := make([]Mutator, len(mlfcb.builders))
	for i := range mlfcb.builders {
		func(i int, root context.Context) {
			builder := mlfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MJLogFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mlfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mlfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mlfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mlfcb *MJLogFileCreateBulk) SaveX(ctx context.Context) []*MJLogFile {
	v, err := mlfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mlfcb *MJLogFileCreateBulk) Exec(ctx context.Context) error {
	_, err := mlfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mlfcb *MJLogFileCreateBulk) ExecX(ctx context.Context) {
	if err := mlfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
