// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanade0404/tenhou-log/services/ent/mjlogfilecompressed"
	"github.com/kanade0404/tenhou-log/services/ent/predicate"
)

// MJLogFileCompressedDelete is the builder for deleting a MJLogFileCompressed entity.
type MJLogFileCompressedDelete struct {
	config
	hooks    []Hook
	mutation *MJLogFileCompressedMutation
}

// Where appends a list predicates to the MJLogFileCompressedDelete builder.
func (mlfcd *MJLogFileCompressedDelete) Where(ps ...predicate.MJLogFileCompressed) *MJLogFileCompressedDelete {
	mlfcd.mutation.Where(ps...)
	return mlfcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mlfcd *MJLogFileCompressedDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mlfcd.hooks) == 0 {
		affected, err = mlfcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MJLogFileCompressedMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mlfcd.mutation = mutation
			affected, err = mlfcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mlfcd.hooks) - 1; i >= 0; i-- {
			if mlfcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mlfcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mlfcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mlfcd *MJLogFileCompressedDelete) ExecX(ctx context.Context) int {
	n, err := mlfcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mlfcd *MJLogFileCompressedDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mjlogfilecompressed.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: mjlogfilecompressed.FieldID,
			},
		},
	}
	if ps := mlfcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mlfcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// MJLogFileCompressedDeleteOne is the builder for deleting a single MJLogFileCompressed entity.
type MJLogFileCompressedDeleteOne struct {
	mlfcd *MJLogFileCompressedDelete
}

// Exec executes the deletion query.
func (mlfcdo *MJLogFileCompressedDeleteOne) Exec(ctx context.Context) error {
	n, err := mlfcdo.mlfcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mjlogfilecompressed.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mlfcdo *MJLogFileCompressedDeleteOne) ExecX(ctx context.Context) {
	mlfcdo.mlfcd.ExecX(ctx)
}
