// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanade0404/tenhou-log/services/ent/mjlogfile"
	"github.com/kanade0404/tenhou-log/services/ent/predicate"
)

// MJLogFileQuery is the builder for querying MJLogFile entities.
type MJLogFileQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MJLogFile
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MJLogFileQuery builder.
func (mlfq *MJLogFileQuery) Where(ps ...predicate.MJLogFile) *MJLogFileQuery {
	mlfq.predicates = append(mlfq.predicates, ps...)
	return mlfq
}

// Limit adds a limit step to the query.
func (mlfq *MJLogFileQuery) Limit(limit int) *MJLogFileQuery {
	mlfq.limit = &limit
	return mlfq
}

// Offset adds an offset step to the query.
func (mlfq *MJLogFileQuery) Offset(offset int) *MJLogFileQuery {
	mlfq.offset = &offset
	return mlfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mlfq *MJLogFileQuery) Unique(unique bool) *MJLogFileQuery {
	mlfq.unique = &unique
	return mlfq
}

// Order adds an order step to the query.
func (mlfq *MJLogFileQuery) Order(o ...OrderFunc) *MJLogFileQuery {
	mlfq.order = append(mlfq.order, o...)
	return mlfq
}

// First returns the first MJLogFile entity from the query.
// Returns a *NotFoundError when no MJLogFile was found.
func (mlfq *MJLogFileQuery) First(ctx context.Context) (*MJLogFile, error) {
	nodes, err := mlfq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mjlogfile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mlfq *MJLogFileQuery) FirstX(ctx context.Context) *MJLogFile {
	node, err := mlfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MJLogFile ID from the query.
// Returns a *NotFoundError when no MJLogFile ID was found.
func (mlfq *MJLogFileQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mlfq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mjlogfile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mlfq *MJLogFileQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mlfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MJLogFile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MJLogFile entity is found.
// Returns a *NotFoundError when no MJLogFile entities are found.
func (mlfq *MJLogFileQuery) Only(ctx context.Context) (*MJLogFile, error) {
	nodes, err := mlfq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mjlogfile.Label}
	default:
		return nil, &NotSingularError{mjlogfile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mlfq *MJLogFileQuery) OnlyX(ctx context.Context) *MJLogFile {
	node, err := mlfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MJLogFile ID in the query.
// Returns a *NotSingularError when more than one MJLogFile ID is found.
// Returns a *NotFoundError when no entities are found.
func (mlfq *MJLogFileQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mlfq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mjlogfile.Label}
	default:
		err = &NotSingularError{mjlogfile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mlfq *MJLogFileQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mlfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MJLogFiles.
func (mlfq *MJLogFileQuery) All(ctx context.Context) ([]*MJLogFile, error) {
	if err := mlfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mlfq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mlfq *MJLogFileQuery) AllX(ctx context.Context) []*MJLogFile {
	nodes, err := mlfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MJLogFile IDs.
func (mlfq *MJLogFileQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := mlfq.Select(mjlogfile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mlfq *MJLogFileQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mlfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mlfq *MJLogFileQuery) Count(ctx context.Context) (int, error) {
	if err := mlfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mlfq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mlfq *MJLogFileQuery) CountX(ctx context.Context) int {
	count, err := mlfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mlfq *MJLogFileQuery) Exist(ctx context.Context) (bool, error) {
	if err := mlfq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mlfq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mlfq *MJLogFileQuery) ExistX(ctx context.Context) bool {
	exist, err := mlfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MJLogFileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mlfq *MJLogFileQuery) Clone() *MJLogFileQuery {
	if mlfq == nil {
		return nil
	}
	return &MJLogFileQuery{
		config:     mlfq.config,
		limit:      mlfq.limit,
		offset:     mlfq.offset,
		order:      append([]OrderFunc{}, mlfq.order...),
		predicates: append([]predicate.MJLogFile{}, mlfq.predicates...),
		// clone intermediate query.
		sql:    mlfq.sql.Clone(),
		path:   mlfq.path,
		unique: mlfq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MJLogFile.Query().
//		GroupBy(mjlogfile.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mlfq *MJLogFileQuery) GroupBy(field string, fields ...string) *MJLogFileGroupBy {
	grbuild := &MJLogFileGroupBy{config: mlfq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mlfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mlfq.sqlQuery(ctx), nil
	}
	grbuild.label = mjlogfile.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.MJLogFile.Query().
//		Select(mjlogfile.FieldName).
//		Scan(ctx, &v)
//
func (mlfq *MJLogFileQuery) Select(fields ...string) *MJLogFileSelect {
	mlfq.fields = append(mlfq.fields, fields...)
	selbuild := &MJLogFileSelect{MJLogFileQuery: mlfq}
	selbuild.label = mjlogfile.Label
	selbuild.flds, selbuild.scan = &mlfq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a MJLogFileSelect configured with the given aggregations.
func (mlfq *MJLogFileQuery) Aggregate(fns ...AggregateFunc) *MJLogFileSelect {
	return mlfq.Select().Aggregate(fns...)
}

func (mlfq *MJLogFileQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mlfq.fields {
		if !mjlogfile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mlfq.path != nil {
		prev, err := mlfq.path(ctx)
		if err != nil {
			return err
		}
		mlfq.sql = prev
	}
	return nil
}

func (mlfq *MJLogFileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MJLogFile, error) {
	var (
		nodes   = []*MJLogFile{}
		withFKs = mlfq.withFKs
		_spec   = mlfq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, mjlogfile.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MJLogFile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MJLogFile{config: mlfq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mlfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mlfq *MJLogFileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mlfq.querySpec()
	_spec.Node.Columns = mlfq.fields
	if len(mlfq.fields) > 0 {
		_spec.Unique = mlfq.unique != nil && *mlfq.unique
	}
	return sqlgraph.CountNodes(ctx, mlfq.driver, _spec)
}

func (mlfq *MJLogFileQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := mlfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (mlfq *MJLogFileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mjlogfile.Table,
			Columns: mjlogfile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: mjlogfile.FieldID,
			},
		},
		From:   mlfq.sql,
		Unique: true,
	}
	if unique := mlfq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mlfq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mjlogfile.FieldID)
		for i := range fields {
			if fields[i] != mjlogfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mlfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mlfq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mlfq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mlfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mlfq *MJLogFileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mlfq.driver.Dialect())
	t1 := builder.Table(mjlogfile.Table)
	columns := mlfq.fields
	if len(columns) == 0 {
		columns = mjlogfile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mlfq.sql != nil {
		selector = mlfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mlfq.unique != nil && *mlfq.unique {
		selector.Distinct()
	}
	for _, p := range mlfq.predicates {
		p(selector)
	}
	for _, p := range mlfq.order {
		p(selector)
	}
	if offset := mlfq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mlfq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MJLogFileGroupBy is the group-by builder for MJLogFile entities.
type MJLogFileGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mlfgb *MJLogFileGroupBy) Aggregate(fns ...AggregateFunc) *MJLogFileGroupBy {
	mlfgb.fns = append(mlfgb.fns, fns...)
	return mlfgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mlfgb *MJLogFileGroupBy) Scan(ctx context.Context, v any) error {
	query, err := mlfgb.path(ctx)
	if err != nil {
		return err
	}
	mlfgb.sql = query
	return mlfgb.sqlScan(ctx, v)
}

func (mlfgb *MJLogFileGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range mlfgb.fields {
		if !mjlogfile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mlfgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mlfgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mlfgb *MJLogFileGroupBy) sqlQuery() *sql.Selector {
	selector := mlfgb.sql.Select()
	aggregation := make([]string, 0, len(mlfgb.fns))
	for _, fn := range mlfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mlfgb.fields)+len(mlfgb.fns))
		for _, f := range mlfgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mlfgb.fields...)...)
}

// MJLogFileSelect is the builder for selecting fields of MJLogFile entities.
type MJLogFileSelect struct {
	*MJLogFileQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mlfs *MJLogFileSelect) Aggregate(fns ...AggregateFunc) *MJLogFileSelect {
	mlfs.fns = append(mlfs.fns, fns...)
	return mlfs
}

// Scan applies the selector query and scans the result into the given value.
func (mlfs *MJLogFileSelect) Scan(ctx context.Context, v any) error {
	if err := mlfs.prepareQuery(ctx); err != nil {
		return err
	}
	mlfs.sql = mlfs.MJLogFileQuery.sqlQuery(ctx)
	return mlfs.sqlScan(ctx, v)
}

func (mlfs *MJLogFileSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(mlfs.fns))
	for _, fn := range mlfs.fns {
		aggregation = append(aggregation, fn(mlfs.sql))
	}
	switch n := len(*mlfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		mlfs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		mlfs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := mlfs.sql.Query()
	if err := mlfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
