// Code generated by ent, DO NOT EDIT.

package gameplayerhandhai

const (
	// Label holds the string label denoting the gameplayerhandhai type in the database.
	Label = "game_player_hand_hai"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the gameplayerhandhai in the database.
	Table = "game_player_hand_hais"
)

// Columns holds all SQL columns for gameplayerhandhai fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
