name: 'Actions'

on:
  pull_request:
  push:
    branches:
      - master
      - feature/*
      - renovate/*
      - dependabot/*
    paths:
      - .github/workflows/*.{yaml|yml}

jobs:
  actions:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
