name: Next CD
on:
  push:
    branches:
      - master
    paths:
      - services/web/**
      - docker/web/**
      - .github/workflows/node-cd.yaml
  workflow_dispatch:
env:
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/web/next
jobs:
  cd:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER_DEV }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions@${{ secrets.GCP_PROJECT_ID_DEV }}.iam.gserviceaccount.com"
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Create docker authentication
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: Build Image
        run: docker build -t ${{ env.IMAGE }} services/web -f docker/web/Dockerfile
      - name: Push Image
        run: docker push ${{ env.IMAGE }}
      - name: Deploy App
        run: gcloud run deploy web --image ${{ env.IMAGE }} --region asia-northeast1
