name: Next CD
on:
  push:
jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install packages
        run: yarn install --production  --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run lint
        run: yarn lint
