name: Parser CI
on:
  pull_request:
    paths:
      - pkg/parser/**
      - .github/workflows/parser-ci.yaml
defaults:
  run:
    shell: bash
    working-directory: pkg/parser
jobs:
  parser-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Test
        run: go test ./...
      - name: Format
        run: go fmt ./...
      - name: go lint
        run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
