name: Terraform CI
on:
  pull_request:
    branches:
      - master
    paths:
      - infra/**
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        envs: [dev]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Authentication Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER_DEV }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions@${{ secrets.GCP_PROJECT_ID_DEV }}.iam.gserviceaccount.com"
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4
      - name: 'Set up Terraform'
        run: terraform init -var-file terraform.tfvars
        working-directory: infra/terraform/env/${{ matrix.envs }}
      - name: Decrypt tfvars
        run: |
          gcloud kms decrypt --location asia-northeast1 --keyring keyring-${{ matrix.envs }} --key terraform --plaintext-file terraform.tfvars --ciphertext-file terraform.tfvars.enc
          gcloud kms decrypt --location asia-northeast1 --keyring keyring-${{ matrix.envs }} --key terraform --plaintext-file credentials/database.json --ciphertext-file credentials/database.json.enc
          gcloud kms decrypt --location asia-northeast1 --keyring keyring-${{ matrix.envs }} --key terraform --plaintext-file credentials/api.json --ciphertext-file credentials/api.json.enc
          gcloud kms decrypt --location asia-northeast1 --keyring keyring-${{ matrix.envs }} --key terraform --plaintext-file credentials/secret.json --ciphertext-file credentials/secret.json.enc
        working-directory: infra/terraform/env/${{ matrix.envs }}
      - name: 'Terraform fmt'
        run: terraform fmt ./...
        working-directory: infra/terraform/env/${{ matrix.envs }}
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
          filter_mode: "nofilter"
          tflint_version: "v1.19.1"
          tflint_rulesets: "google"
          working_directory: infra/terraform/env/${{ matrix.envs }}
      - name: 'Install tfcmt'
        run: |
          sudo curl -fL -o tfcmt.tar.gz https://github.com/suzuki-shunsuke/tfcmt/releases/download/${{ env.TFCMT_VERSION }}/tfcmt_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfcmt.tar.gz
        env:
          TFCMT_VERSION: v4.3.0
      - name: Terraform Plan
        run: tfcmt plan -- terraform plan -var-file=terraform.tfvars --no-color
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.number }}
        working-directory: infra/terraform/env/${{ matrix.envs }}
